name: Publish Drafts

on:
  schedule:
    - cron: '22 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Jekyll Publish Drafts
      uses: soywiz-archive/github-action-jekyll-publish-drafts@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_path: ./
        branch: main

